---
version: "3.9"
services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: "azurite"
    hostname: azurite
    restart: always
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
  mssqldb:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: "mssqldb"
    environment:
      - "ACCEPT_EULA=Y"
      - "MSSQL_SA_PASSWORD=testPASS123"
    hostname: mssqldb
    restart: always
    ports:
      - "1433:1433"
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: "atsapi"
    hostname: ataspi
    environment:
      - "DATABASE__DATASOURCE=mssqldb"
      - "DATABASE__PASSWORD=testPASS123"
      - "DATABASE__USERNAME=sa"
      - "AZURESTORATE__ENDPOINT=http://127.0.0.1:10000"
      - "AZURESTORAGE__ACCOUNT_NAME=devstoreaccount1"
      - "AZURESTORAGE__ACCOUNT_KEY=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==1"
      - "JWT__SECRET=ATS"
      - "ALLOWEDORIGINS=http://localhost:4200"
    restart: always
    ports:
      - "7057:8080"
