---
version: "3.9"
services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: "azurite"
    hostname: azurite
    restart: always
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    command: azurite --skipApiVersionCheck --blobHost 0.0.0.0 --blobPort 10000
  mssqldb:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: "mssqldb"
    environment:
      - "ACCEPT_EULA=Y"
      - "MSSQL_SA_PASSWORD=testPASS123"
    hostname: mssqldb
    restart: always
    volumes:
      - ./db:/var/atsdb
    ports:
      - "1433:1433"
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: "atsapi"
    hostname: ataspi
    environment:
      - "DATABASE__DATASOURCE=mssqldb"
      - "DATABASE__PASSWORD=testPASS123"
      - "DATABASE__USERNAME=sa"
      - "AZURESTORAGE__ENDPOINT=http://azurite:10000"
      - "AZURESTORAGE__ACCOUNT__NAME=devstoreaccount1"
      - "AZURESTORAGE__ACCOUNT__KEY=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw=="
      - "JWT__SECRET=ATS"
      - "ALLOWEDORIGINS=http://localhost:100"
    restart: always
    ports:
      - "7057:8080"
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: "atsui"
    hostname: atsui
    restart: always
    ports:
      - "100:80"
  azurite-seed:
    image: mcr.microsoft.com/azure-cli:latest
    volumes:
      - ./db:/var/atsdb
    depends_on:
      - azurite
    entrypoint: /bin/sh /var/atsdb/azstorage.sh
  mssqldb-seed:
    image: mcr.microsoft.com/mssql-tools:latest
    volumes:
      - ./db:/var/atsdb
    depends_on:
      - mssqldb
    entrypoint: /bin/bash /var/atsdb/seed.sh