DROP TABLE Picture;
DROP TABLE UserAccount;
DROP TABLE Role;
DROP TABLE AreaYear;
DROP TABLE Area;
DROP TABLE Year;

DELETE Picture;
DELETE AreaYear;
DELETE Area;
DELETE Year;
DELETE UserAccount;
DELETE Role;