CREATE TABLE Year
(
    YearID INT IDENTITY(1, 1) PRIMARY KEY,
    Value INT NOT NULL UNIQUE
);

CREATE TABLE Area
(
    AreaID INT IDENTITY(1, 1) PRIMARY KEY,
    ParentID INT NULL,
    Name NVARCHAR(128),
    CONSTRAINT FK_ChildAreaID FOREIGN KEY (ParentID) REFERENCES Area(AreaID)
);

CREATE TABLE AreaYear
(
    AreaID INT NOT NULL,
    YearID INT NOT NULL,
    CONSTRAINT PK_AreaYear PRIMARY KEY (AreaID, YearID),
    CONSTRAINT FK_AreaYear_AreaID FOREIGN KEY (AreaID) REFERENCES Area(AreaID),
    CONSTRAINT FK_AreaYear_YearID FOREIGN KEY (YearID) REFERENCES Year(YearID),
);

CREATE TABLE Picture
(
    PictureID BIGINT IDENTITY(1, 1) PRIMARY KEY,
    AreaID INT NOT NULL,
    Title NVARCHAR(400) NOT NULL,
    Description NVARCHAR(4000) NULL,
    CONSTRAINT FK_AreaID FOREIGN KEY (AreaID) REFERENCES Area(AreaID)
);

