CREATE TABLE Role
(
    RoleID INT IDENTITY(1, 1) PRIMARY KEY,
    Name VARCHAR(10) NOT NULL UNIQUE
);

CREATE TABLE UserAccount
(
    UserAccountID BIGINT IDENTITY(1, 1) PRIMARY KEY,
    RoleID INT NOT NULL,
    Username NVARCHAR(100) NOT NULL UNIQUE,
    Password VARCHAR(128) NOT NULL,
    IsActive BIT NOT NULL,
    CONSTRAINT FK_RoleID FOREIGN KEY (RoleID) REFERENCES Role(RoleID)
);

CREATE TABLE Year
(
    YearID INT IDENTITY(1, 1) PRIMARY KEY,
    Value INT NOT NULL UNIQUE
);

CREATE TABLE Area
(
    AreaID INT IDENTITY(1, 1) PRIMARY KEY,
    ParentID INT NULL,
    Name NVARCHAR(128),
    CONSTRAINT FK_ChildAreaID FOREIGN KEY (ParentID) REFERENCES Area(AreaID)
);

CREATE TABLE AreaYear
(
    AreaID INT NOT NULL,
    YearID INT NOT NULL,
    CONSTRAINT PK_AreaYear PRIMARY KEY (AreaID, YearID),
    CONSTRAINT FK_AreaYear_AreaID FOREIGN KEY (AreaID) REFERENCES Area(AreaID),
    CONSTRAINT FK_AreaYear_YearID FOREIGN KEY (YearID) REFERENCES Year(YearID),
);

CREATE TABLE Picture
(
    PictureID BIGINT IDENTITY(1, 1) PRIMARY KEY,
    AreaID INT NOT NULL,
    Extension NVARCHAR(10) NOT NULL,
    Title NVARCHAR(400) NOT NULL,
    Description NVARCHAR(4000) NULL,
    IsActive BIT NOT NULL,
    CreatedOn DATETIME2 NOT NULL,
    UpdatedOn DATETIME2 NOT NULL,
    CreatedBy BIGINT NOT NULL,
    UpdatedBy BIGINT NOT NULL,
    CONSTRAINT FK_AreaID FOREIGN KEY (AreaID) REFERENCES Area(AreaID),
    CONSTRAINT FK_CreatedBy FOREIGN KEY (CreatedBy) REFERENCES UserAccount(UserAccountID),
    CONSTRAINT FK_UpdatedBy FOREIGN KEY (UpdatedBy) REFERENCES UserAccount(UserAccountID)
);
